[package]
name = "fei-common"
version = "0.1.0"
edition = "2021"

[dependencies]
fei-common-macros = { path = "macros" }

anyhow = "^1.0"
fixedbitset = "0.4"
fxhash = "0.2"
hashbrown = { version = "0.14", features = ["inline-more"] }
parking_lot = "0.12"
