[package]
name = "fei-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "^1.0"
syn = "^2.0"
quote = "^1.0"

[dependencies.toml]
version = "0.8"
default-features = false
features = ["parse"]
